package com.ssakura49.sakuratinker.register;

import com.ssakura49.sakuratinker.SakuraTinker;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.armor.*;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.armor.IngaRyu.IngaRyuModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.curio.*;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.melee.*;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.melee.soulDevourerModifier.SoulDevourerModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.mining.BedrockBreakerModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.mining.BreakSpeedModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.misc.*;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.misc.treasuremodifier.TreasureModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.ranged.CrackShotModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.ranged.PrecisionStrikeModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.special.*;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.special.battleflag.AttackModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.special.battleflag.DefenceModifier;
import com.ssakura49.sakuratinker.common.tinkering.modifiers.test.test;
import com.ssakura49.sakuratinker.compat.IceAndFireCompat.modifiers.BreathResistanceModifier;
import com.ssakura49.sakuratinker.compat.IceAndFireCompat.modifiers.DragonMartyrModifier;
import com.ssakura49.sakuratinker.compat.IronSpellBooks.modifiers.EnchantedBladeModifier;
import com.ssakura49.sakuratinker.compat.IronSpellBooks.modifiers.MagicShieldModifier;
import slimeknights.tconstruct.library.modifiers.Modifier;
import slimeknights.tconstruct.library.modifiers.impl.NoLevelsModifier;
import slimeknights.tconstruct.library.modifiers.util.ModifierDeferredRegister;
import slimeknights.tconstruct.library.modifiers.util.StaticModifier;

public class STModifiers {

    public STModifiers() {
    }

    public static ModifierDeferredRegister MODIFIERS = ModifierDeferredRegister.create(SakuraTinker.MODID);

    public static StaticModifier<SolidModifier> Solid;
    public static StaticModifier<VoidModifier> Void;
    public static StaticModifier<WitherSymbiosisModifier> Wither_Symbiosis;
    public static StaticModifier<CelestialModifier> Celestial;
    public static StaticModifier<RuinationModifier> Ruination;
    public static StaticModifier<EternityModifier> Eternity;
    public static StaticModifier<NullAlmightyModifier> Null_Almighty;
    public static StaticModifier<MortalWoundModifier> Mortal_Wound;
    public static StaticModifier<KoboldModifier> Kobold;
    public static StaticModifier<StormVeilModifier> Storm_Veil;
    public static StaticModifier<RootednessModifier> Rootedness;
    public static StaticModifier<NetherGhostModifier> Nether_Ghost;
    public static StaticModifier<GaleModifier> Gale;
    public static StaticModifier<EvilEyeModifier> Evil_Eye;
    public static StaticModifier<OmnipotenceModifier> Omnipotence;
    public static StaticModifier<GuardianShellModifier> GuardianShell;
    public static StaticModifier<BodyImpactModifier> BodyImpact;
    public static StaticModifier<SpectralModifier> Spectral;
    public static StaticModifier<HardenedSkinModifier> HardenedSkin;
    public static StaticModifier<DisslovingModifier> Dissloving;
    public static StaticModifier<GreedyModifier> Greedy;
    public static StaticModifier<EnergyInfusionModifier> EnergyInfusion;
    public static StaticModifier<SoulSiphonModifier> SoulSiphon;
    public static StaticModifier<InfinitumModifier> Infinitum;
    public static StaticModifier<PainResonanceModifier> PainResonance;
    public static StaticModifier<NeutronCondenseModifier> NeutronCondense;
    public static StaticModifier<AbsorptionModifier> Absorption;
    public static StaticModifier<JinxDollModifier> JinxDoll;
    public static StaticModifier<ColorizationModifier> Colorization;
    public static StaticModifier<HeavyModifier> Heavy;
    public static StaticModifier<SwiftSwordTechniqueModifier> SwiftSwordTechnique;
    public static StaticModifier<MambaModifier> Mamba;
    public static StaticModifier<DwarvenCurioModifier> DwarvenCurio;
    public static StaticModifier<LaceratingCurioModifier> LaceratingCurio;
    public static StaticModifier<MagneticCurioModifier> MagneticCurio;
    public static StaticModifier<LightWeightCurioModifier> LightWeightCurio;
    public static StaticModifier<WorldBottomModifier> WorldBottom;
    public static StaticModifier<HighFrequencyBarrierModifier> HighFrequencyBarrier;
    public static StaticModifier<BladeConvergenceModifier> BladeConvergence;
    public static StaticModifier<TorturingModifier> Torturing;
    public static StaticModifier<CrystallineModifier> Crystalline;
    public static StaticModifier<CrystallineArmorModifier> CrystallineArmor;
    public static StaticModifier<ReapersBlessingModifier> ReapersBlessing;
    public static StaticModifier<BedrockBreakerModifier> BedrockBreaker;
    public static StaticModifier<EnergyDisplayModifier> EnergyDisplay;
    public static StaticModifier<ThunderModifier> Thunder;
    public static StaticModifier<FieryFireModifier> FieryFire;
    public static StaticModifier<FrozenModifier> Frozen;
    public static StaticModifier<FireImmunityModifier> FireImmunity;
    public static StaticModifier<IceImmunityModifier> IceImmunity;
    public static StaticModifier<LightningImmunityModifier> LightningImmunity;
    public static StaticModifier<ChainLightningModifier> ChainLightning;
    public static StaticModifier<DragonSoulModifier> DragonSoul;
    public static StaticModifier<SoulDevourerModifier> SoulDevourer;
    public static StaticModifier<ShieldingModifier> Shielding;
    public static StaticModifier<SteadyCurioModifier> SteadyCurio;
    public static StaticModifier<InsatiableCurioModifier> InsatiableCurio;
    public static StaticModifier<ArrowAmmo> ArrowAmmo;
    public static StaticModifier<EssenceEarthModifier> EssenceEarth;
    public static StaticModifier<HeavyWeightModifier> HeavyWeight;
    public static StaticModifier<MagicBladeModifier> MagicBlade;
    public static StaticModifier<SpellPowerModifier> SpellPower;
    public static StaticModifier<SolarBurningModifier> SolarBurning;
    public static StaticModifier<RejuvenatingModifier> Rejuvenating;
    public static StaticModifier<SealTooltipModifier> SealTooltip;
    public static StaticModifier<FeatherModifier> Feather;
    public static StaticModifier<HydraWillModifier> HydraWill;
    public static StaticModifier<PrecisionStrikeModifier> PrecisionStrike;
    public static StaticModifier<EnergySurge> EnergySurge;
    public static StaticModifier<Modifier> Whetstone;
    public static StaticModifier<PolishModifier> Polish;
    public static StaticModifier<PolishingModifier> Polishing;
    public static StaticModifier<LifeRatioDamageModifier> LifeRatioDamage;
    public static StaticModifier<AttackModifier> ATTACK_MODIFIER;
    public static StaticModifier<DefenceModifier> DEFENCE_MODIFIER;
    public static StaticModifier<StrengthenDecompositionModifier> StrengthenDecomposition;
    public static StaticModifier<FungalParasitesModifier> FungalParasites;
    public static StaticModifier<CoagulationModifier> Coagulation;
    public static StaticModifier<DangerSenseModifier> DangerSense;
    public static StaticModifier<IncompleteTransformationModifier> IncompleteTransformation;
    public static StaticModifier<MucilaginousShellModifier> MucilaginousShell;
    public static StaticModifier<FusionBurnModifier> FusionBurn;
    public static StaticModifier<GodOfSlimeModifier> GodOfSlime;
    public static StaticModifier<MindModifier> Mind;
    public static StaticModifier<SoulModifier> Soul;
    public static StaticModifier<ShitakusoModifier> Shitakuso;
    public static StaticModifier<ExceptionallyTalentedModifier> ExceptionallyTalented;
    public static StaticModifier<NoLevelsModifier> Natural_Will;
    public static StaticModifier<RelentlessModifier> Relentless;
    public static StaticModifier<DoubleStrikeModifier> DoubleStrike;
    public static StaticModifier<ResilientGuardModifier> ResilientGuard;
//    public static StaticModifier<TerraPrismaSummonModifier> TerraPrismaSummon;
    public static StaticModifier<HyperBurstModifier> HyperBurst;
    public static StaticModifier<IngaRyuModifier> IngaRyu;
    public static StaticModifier<CrackShotModifier> CrackShot;
    public static StaticModifier<DragonMartyrModifier> DragonMartyr;
    public static StaticModifier<BreathResistanceModifier> BreathResistance;
    public static StaticModifier<ScytheSweepingModifier> ScytheSweeping;

    public static StaticModifier<MagicShieldModifier> MagicShield;
    public static StaticModifier<EnchantedBladeModifier> EnchantedBlade;

    public static StaticModifier<test> test = MODIFIERS.register("test",test::new);

    public static StaticModifier<NoLevelsModifier> G_SOUL_INFUSION;
    public static StaticModifier<BreakSpeedModifier> BreakSpeed;
    public static StaticModifier<AgileModifier> Agile;
    public static StaticModifier<HollowModifier> Hollow;
    public static StaticModifier<HeavenHasFallenModifier> HeavenHasFallen;
    public static StaticModifier<SuperLuckModifier> SuperLuck;
    public static StaticModifier<TreasureModifier> Treasure;
    public static StaticModifier<EngravingModifier> Engraving;
    public static StaticModifier<BloodBurnModifier> BloodBurn;
    public static StaticModifier<DeadlyBulletModifier> DeadlyBullet;

    public static StaticModifier<AlchemicalModifier> Alchemical;

    public static StaticModifier<RevolverBulletModifier> RevolverBullet;

    static {
        Solid = MODIFIERS.register("solid", SolidModifier::new);
        Void = MODIFIERS.register("void", VoidModifier::new);
        Wither_Symbiosis = MODIFIERS.register("wither_symbiosis", WitherSymbiosisModifier::new);
        Celestial = MODIFIERS.register("celestial", CelestialModifier::new);
        Ruination = MODIFIERS.register("ruination", RuinationModifier::new);
        Eternity = MODIFIERS.register("eternity", EternityModifier::new);
        Null_Almighty = MODIFIERS.register("null_almighty", NullAlmightyModifier::new);
        Mortal_Wound = MODIFIERS.register("mortal_wound", MortalWoundModifier::new);
        Kobold = MODIFIERS.register("kobold", KoboldModifier::new);
        Storm_Veil = MODIFIERS.register("storm_veil", StormVeilModifier::new);
        Rootedness = MODIFIERS.register("rootedness", RootednessModifier::new);
        Nether_Ghost = MODIFIERS.register("nether_ghost", NetherGhostModifier::new);
        Gale = MODIFIERS.register("gale", GaleModifier::new);
        Evil_Eye = MODIFIERS.register("evil_eye", EvilEyeModifier::new);
        Omnipotence = MODIFIERS.register("omnipotence", OmnipotenceModifier::new);
        GuardianShell = MODIFIERS.register("guardian_shell", GuardianShellModifier::new);
        BodyImpact = MODIFIERS.register("body_impact", BodyImpactModifier::new);
        Spectral = MODIFIERS.register("spectral", SpectralModifier::new);
        HardenedSkin = MODIFIERS.register("hardened_skin", HardenedSkinModifier::new);
        Dissloving = MODIFIERS.register("dissloving", DisslovingModifier::new);
        Greedy = MODIFIERS.register("greedy", GreedyModifier::new);
        EnergyInfusion = MODIFIERS.register("energy_infusion", EnergyInfusionModifier::new);
        SoulSiphon = MODIFIERS.register("soul_siphon", SoulSiphonModifier::new);
        Infinitum = MODIFIERS.register("infinitum", InfinitumModifier::new);
        PainResonance = MODIFIERS.register("pain_resonance", PainResonanceModifier::new);
        NeutronCondense = MODIFIERS.register("neutron_condense", NeutronCondenseModifier::new);
        Absorption = MODIFIERS.register("absorption", AbsorptionModifier::new);
        JinxDoll = MODIFIERS.register("jinx_doll", JinxDollModifier::new);
        Colorization = MODIFIERS.register("colorization", ColorizationModifier::new);
        Heavy = MODIFIERS.register("heavy", HeavyModifier::new);
        SwiftSwordTechnique = MODIFIERS.register("swift_sword_technique", SwiftSwordTechniqueModifier::new);
        Mamba = MODIFIERS.register("mamba", MambaModifier::new);
        DwarvenCurio = MODIFIERS.register("dwarven_curio", DwarvenCurioModifier::new);
        LaceratingCurio = MODIFIERS.register("lacerating_curio", LaceratingCurioModifier::new);
        MagneticCurio = MODIFIERS.register("magnetic_curio", MagneticCurioModifier::new);
        LightWeightCurio = MODIFIERS.register("light_weight_curio", LightWeightCurioModifier::new);
        WorldBottom = MODIFIERS.register("world_bottom", WorldBottomModifier::new);
        HighFrequencyBarrier = MODIFIERS.register("high_frequency_barrier", HighFrequencyBarrierModifier::new);
        BladeConvergence = MODIFIERS.register("blade_convergence", BladeConvergenceModifier::new);
        Torturing = MODIFIERS.register("torturing", TorturingModifier::new);
        Crystalline = MODIFIERS.register("crystalline", CrystallineModifier::new);
        CrystallineArmor = MODIFIERS.register("crystalline_armor", CrystallineArmorModifier::new);
        ReapersBlessing = MODIFIERS.register("reapers_blessing", ReapersBlessingModifier::new);
        BedrockBreaker = MODIFIERS.register("bedrock_breaker", BedrockBreakerModifier::new);
        EnergyDisplay = MODIFIERS.register("energy_display", EnergyDisplayModifier::new);
        Thunder = MODIFIERS.register("thunder", ThunderModifier::new);
        FieryFire = MODIFIERS.register("fiery_fire", FieryFireModifier::new);
        Frozen = MODIFIERS.register("frozen", FrozenModifier::new);
        FireImmunity = MODIFIERS.register("fire_immunity", FireImmunityModifier::new);
        IceImmunity = MODIFIERS.register("ice_immunity", IceImmunityModifier::new);
        LightningImmunity = MODIFIERS.register("lightning_immunity", LightningImmunityModifier::new);
        ChainLightning = MODIFIERS.register("chain_lightning", ChainLightningModifier::new);
        DragonSoul = MODIFIERS.register("dragon_soul", DragonSoulModifier::new);
        SoulDevourer = MODIFIERS.register("soul_devourer", SoulDevourerModifier::new);
        Shielding = MODIFIERS.register("shielding", ShieldingModifier::new);
        SteadyCurio = MODIFIERS.register("steady_curio", SteadyCurioModifier::new);
        InsatiableCurio = MODIFIERS.register("insatiable_curio", InsatiableCurioModifier::new);
        ArrowAmmo = MODIFIERS.register("arrow_ammo", ArrowAmmo::new);
        EssenceEarth = MODIFIERS.register("essence_earth", EssenceEarthModifier::new);
        HeavyWeight = MODIFIERS.register("heavy_weight", HeavyWeightModifier::new);
        MagicBlade = MODIFIERS.register("magic_blade", MagicBladeModifier::new);
        SpellPower = MODIFIERS.register("spell_power", SpellPowerModifier::new);
        SolarBurning = MODIFIERS.register("solar_burning", SolarBurningModifier::new);
        Rejuvenating = MODIFIERS.register("rejuvenating", RejuvenatingModifier::new);
        SealTooltip = MODIFIERS.register("seal_tooltip", SealTooltipModifier::new);
        Feather = MODIFIERS.register("feather", FeatherModifier::new);
        HydraWill = MODIFIERS.register("hydra_will", HydraWillModifier::new);
        PrecisionStrike = MODIFIERS.register("precision_strike", PrecisionStrikeModifier::new);
        EnergySurge = MODIFIERS.register("energy_surge", EnergySurge::new);
        Whetstone = MODIFIERS.register("whetstone", Modifier::new);
        Polish = MODIFIERS.register("polish", PolishModifier::new);
        Polishing = MODIFIERS.register("polishing", PolishingModifier::new);
        LifeRatioDamage = MODIFIERS.register("life_ratio", LifeRatioDamageModifier::new);
        ATTACK_MODIFIER = MODIFIERS.register("attack_modifier", AttackModifier::new);
        DEFENCE_MODIFIER = MODIFIERS.register("defence_modifier", DefenceModifier::new);
        StrengthenDecomposition = MODIFIERS.register("strengthen_decomposition", StrengthenDecompositionModifier::new);
        FungalParasites = MODIFIERS.register("fungal_parasites", FungalParasitesModifier::new);
        Coagulation = MODIFIERS.register("coagulation", CoagulationModifier::new);
        DangerSense = MODIFIERS.register("danger_sense", DangerSenseModifier::new);
        IncompleteTransformation = MODIFIERS.register("incomplete_transformation", IncompleteTransformationModifier::new);
        MucilaginousShell = MODIFIERS.register("mucilaginous_shell", MucilaginousShellModifier::new);
        FusionBurn = MODIFIERS.register("fusion_burn", FusionBurnModifier::new);
        GodOfSlime = MODIFIERS.register("god_of_slime", GodOfSlimeModifier::new);

        Mind = MODIFIERS.register("mind", MindModifier::new);
        Soul = MODIFIERS.register("soul", SoulModifier::new);
        Shitakuso = MODIFIERS.register("shitakuso", ShitakusoModifier::new);
        ExceptionallyTalented = MODIFIERS.register("exceptionally_talented", ExceptionallyTalentedModifier::new);
        Natural_Will = MODIFIERS.register("natural_will", NoLevelsModifier::new);
        Relentless = MODIFIERS.register("relentless", RelentlessModifier::new);
        DoubleStrike = MODIFIERS.register("double_strike", DoubleStrikeModifier::new);
        ResilientGuard = MODIFIERS.register("resilient_guard",ResilientGuardModifier::new);
//        TerraPrismaSummon = MODIFIERS.register("terra_prisma_summon", TerraPrismaSummonModifier::new);
        HyperBurst = MODIFIERS.register("hyper_burst", HyperBurstModifier::new);
        IngaRyu = MODIFIERS.register("inga_ryu", IngaRyuModifier::new);
        CrackShot = MODIFIERS.register("crack_shot", CrackShotModifier::new);
        DragonMartyr = MODIFIERS.register("dragon_martyr", DragonMartyrModifier::new);
        BreathResistance = MODIFIERS.register("breath_resistance", BreathResistanceModifier::new);
        ScytheSweeping = MODIFIERS.register("scythe_sweeping", ScytheSweepingModifier::new);
        MagicShield = MODIFIERS.register("magic_shield", MagicShieldModifier::new);
        EnchantedBlade = MODIFIERS.register("enchanted_blade", EnchantedBladeModifier::new);
        G_SOUL_INFUSION = MODIFIERS.register("g_soul_infusion", NoLevelsModifier::new);
        BreakSpeed = MODIFIERS.register("break_speed", BreakSpeedModifier::new);
        Agile = MODIFIERS.register("agile",AgileModifier::new);
        Hollow = MODIFIERS.register("hollow", HollowModifier::new);
        HeavenHasFallen = MODIFIERS.register("heaven_fallen", HeavenHasFallenModifier::new);
        SuperLuck = MODIFIERS.register("super_luck", SuperLuckModifier::new);
        Treasure = MODIFIERS.register("treasure", TreasureModifier::new);
        Engraving = MODIFIERS.register("engraving", EngravingModifier::new);
        BloodBurn = MODIFIERS.register("blood_burn", BloodBurnModifier::new);
        DeadlyBullet = MODIFIERS.register("deadly_bullet", DeadlyBulletModifier::new);
        Alchemical = MODIFIERS.register("alchemical",AlchemicalModifier::new);
        RevolverBullet = MODIFIERS.register("revolver_bullet",RevolverBulletModifier::new);
    }
}
